# Generated by Django 4.2.1 on 2023-05-16 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('long_name', models.CharField(blank=None, max_length=100, null=None)),
                ('popularity', models.IntegerField(blank=None, null=None)),
                ('updated_date', models.DateField(blank=None, default=datetime.date.today, null=None)),
            ],
        ),
    ]
